<a href="https://colab.research.google.com/github/Alok-Senapati/Collab-Notebooks/blob/main/numpy/Numpy%20Indexing%20%26%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
## 1. Slicing -> To Access Contiguous Elements
arr = np.array([2, 4, 3, 1, 7])
print(arr[1:3])
print(arr[:4])
print(arr[2:])
print(arr[:-1])
print(arr[-4:-2])

[4 3]
[2 4 3 1]
[3 1 7]
[2 4 3 1]
[4 3]


In [3]:
## Slicing in 2D Array
mat = np.array([
    [2, 4, 5],
    [6, 9, 1],
    [7, 8, 10],
    [1, 7, 3]
])
## mat[row_slice, col_slice]
print(mat[:2, 0:2])
print(mat[:, :2])
print(mat[:-1, :-1])
print(mat[0:2])

[[2 4]
 [6 9]]
[[2 4]
 [6 9]
 [7 8]
 [1 7]]
[[2 4]
 [6 9]
 [7 8]]
[[2 4 5]
 [6 9 1]]


In [4]:
## Fancy Indexing: Passing a list of indexes to select. The order of elements in output is same as order of input index list
print(arr[[0, 3, 2]])
print(arr[[3, 3, 2, 1, 4, 0]])

[2 1 3]
[1 1 3 4 7 2]


In [5]:
## Matrix Fancy Indexing: mat[row_idx, col_idx]
print(mat[[0, 2], [2, 1]])
print(mat[[2, 2, 1, 0], [1, 0, 0, 2]])
print(mat[:-1, [2, 0, 1]]) ## Slicing + Fancy Indexing

[5 8]
[8 7 6 5]
[[ 5  2  4]
 [ 1  6  9]
 [10  7  8]]


## Element-wise Operations

NumPy performs operations on **every element** simultaneously without explicit loops. This is called **vectorization**.

In [6]:
## List vs Array Behaviour -> Behaves differently with same operation.
print([1, 2, 3] + [3, 4, 5]) ## Concatenation
print(np.array([1, 2, 3]) + np.array([3, 4, 5])) ## Element wise addition

[1, 2, 3, 3, 4, 5]
[4 6 8]


In [7]:
print([1, 2, 3] * 3)
print(np.array([1, 2, 3]) * 3) ## Scalar Multiplication

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [8]:
## Scalar Operation -> Scalar value is broadcasted to operate with each element
arr = np.arange(1, 10)

print(arr + 5)
print(arr * 5)
print(arr - 5)
print(arr / 5)
print(arr // 5)
print(arr % 5)
print(arr ** 2)

[ 6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45]
[-4 -3 -2 -1  0  1  2  3  4]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[0 0 0 0 1 1 1 1 1]
[1 2 3 4 0 1 2 3 4]
[ 1  4  9 16 25 36 49 64 81]


In [9]:
## Element Wise Operation
first = np.array([1, 2, 3, 4])
second = np.array([8, 7, 6, 5])

print(first + second)
print(second - first)
print(first * second)
print(second / first)
print(second // first)
print(second ** first)

[9 9 9 9]
[7 5 3 1]
[ 8 14 18 20]
[8.   3.5  2.   1.25]
[8 3 2 1]
[  8  49 216 625]


In [10]:
## Comparison Operators -> Return Boolean Arrays which can be used as Boolean masks for filtering
scores = np.random.randint(20, 100, size=10)
print(scores)

print(scores > 30)
print(scores >= 45)
print(scores != 74)

## Logical Operators. Always use () while using logical operators for np arrays
print((scores > 30) & (scores < 80))
print((scores < 50) | (scores >= 76))
print(~(scores % 2 == 0))

## Using as boolean mask to filter elements
print(scores[scores > 30])
print(scores[(scores < 50) | (scores >= 76)])

[29 44 95 78 54 31 39 44 27 63]
[False  True  True  True  True  True  True  True False  True]
[False False  True  True  True False False False False  True]
[ True  True  True  True  True  True  True  True  True  True]
[False  True False  True  True  True  True  True False  True]
[ True  True  True  True False  True  True  True  True False]
[ True False  True False False  True  True False  True  True]
[44 95 78 54 31 39 44 63]
[29 44 95 78 31 39 44 27]


In [11]:
mat = np.random.randint(20, 100, size=12).reshape(4, 3)

print(mat)
print(mat > 50)
print(mat[mat > 50]) ## Returns Array

[[32 95 86]
 [75 46 44]
 [47 54 82]
 [86 30 42]]
[[False  True  True]
 [ True False False]
 [False  True  True]
 [ True False False]]
[95 86 75 54 82 86]


## Broadcasting

Broadcasting allows NumPy to work with arrays of different shapes by automatically "stretching" smaller arrays.

In [12]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Array + 10:", arr + 10)  # 10 broadcasts to all elements

# Conceptually, this is like:
# [1, 2, 3, 4, 5] + [10, 10, 10, 10, 10] = [11, 12, 13, 14, 15]

Array: [1 2 3 4 5]
Array + 10: [11 12 13 14 15]


### 1D + 2D Broadcasting

A 1D array can broadcast across the rows (or columns) of a 2D array if the shapes are compatible.

In [13]:
# 2D matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 1D array (must match the number of columns)
row = np.array([10, 20, 30])

print("Matrix (2x3):")
print(matrix)
print("\nRow (1D):", row)

print("\nMatrix + Row:")
print(matrix + row)
# The row broadcasts across EACH row of the matrix

Matrix (2x3):
[[1 2 3]
 [4 5 6]]

Row (1D): [10 20 30]

Matrix + Row:
[[11 22 33]
 [14 25 36]]


In [14]:
## An array of lesser dimension can be broadcasted to an array of higher dimention, if and only if
##  The lower dims of the bigger array are either of same shape or either one of them is 1.

arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.array([1, 2, 3, 4])
print(arr1.shape) # (3, 4)
print(arr2.shape) # (4,)

## Broadcasts arr2 to make it shape (1, 4), Now columns are of same shape and one of the row shape is 1, Hence it makes arr2 (3, 4) by repeating column to 3 rows.
print(arr1 + arr2)


(3, 4)
(4,)
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [15]:
arr3 = np.ones((2, 3, 4))
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr3.shape)
print(arr4.shape)

print(arr3 + arr4)

(2, 3, 4)
(3, 3)


ValueError: operands could not be broadcast together with shapes (2,3,4) (3,3) 

In [16]:
arr5 = np.array([[1, 2, 3, 4], [7, 4, 8, 10]])
arr6 = np.array([[3], [7]])

print(arr5.shape)
print(arr6.shape)

print(arr5 + arr6)


(2, 4)
(2, 1)
[[ 4  5  6  7]
 [14 11 15 17]]


### Using np.where()

`np.where()` has two main uses:
1. Find indices where condition is True: `np.where(condition)`
2. Conditional replacement: `np.where(condition, value_if_true, value_if_false)`

In [17]:
# Find INDICES where condition is True
scores = np.array([45, 67, 82, 55, 90, 38, 75])
indices = np.where(scores >= 60)
print("Indices where scores >= 60:", indices)
print("Just the indices:", indices[0])  # Extract from tuple

Indices where scores >= 60: (array([1, 2, 4, 6]),)
Just the indices: [1 2 4 6]


In [18]:
print(np.where(scores > 68, "Pass", "Fail"))

['Fail' 'Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [19]:
temps = np.array([15, 22, 28, 19, 31, 17, 24, 12, 26])

# Your code here:
# 1. Find all temperatures above 25
print(temps[temps > 25])


# 2. Find temperatures in range 18-26 (inclusive)
print(temps[(temps >= 18) & (temps <= 26)])


# 3. Label as Hot/Cold/OK (hint: use nested np.where)
print(np.where(temps > 25, 'Hot', np.where(temps < 18, 'Cold', 'OK')))

[28 31 26]
[22 19 24 26]
['Cold' 'OK' 'Hot' 'OK' 'Hot' 'Cold' 'OK' 'Cold' 'Hot']


## Universal Functions (ufuncs)

Universal functions operate on every element of an array (or across specific axes).

**Key insight for aggregations:** The `axis` parameter controls the direction of the operation.
- `axis=0`: Operate DOWN columns (rows collapse)
- `axis=1`: Operate ACROSS rows (columns collapse)

**Memory trick:** "The axis you specify is the axis that DISAPPEARS."

### Aggregation Functions

Common aggregations: `np.sum()`, `np.mean()`, `np.std()`, `np.min()`, `np.max()`

In [20]:
## 3 Students * 4 Subjects
grades = np.array([[85, 90, 78, 92],
                   [88, 76, 95, 85],
                   [90, 88, 82, 79]])

In [21]:
# Aggregation over ALL elements
print("=== All Elements ===")
print(f"Sum of all grades: {np.sum(grades)}")
print(f"Mean of all grades: {np.mean(grades):.2f}")
print(f"Std deviation: {np.std(grades):.2f}")
print(f"Min grade: {np.min(grades)}")
print(f"Max grade: {np.max(grades)}")

=== All Elements ===
Sum of all grades: 1028
Mean of all grades: 85.67
Std deviation: 5.68
Min grade: 76
Max grade: 95


In [22]:
# Average in each subject
print(np.round(np.mean(grades, axis=0), 2))

[87.67 84.67 85.   85.33]


In [23]:
# Total Score of each student.
print(np.sum(grades, axis=1))

[345 344 339]


In [24]:
# Max score in each subject
print(np.max(grades, axis=0))

# Max score of each student
print(np.max(grades, axis=1))

[90 90 95 92]
[92 95 90]


In [25]:
### Mathematical Functions
print(np.sqrt(np.array([25, 36, 16])))
e = np.exp(np.array([0, 1, -1]))
print(e)
print(np.log(e))

[5. 6. 4.]
[1.         2.71828183 0.36787944]
[ 0.  1. -1.]


In [26]:
sales = np.array([[150, 200, 180],
                  [220, 190, 240],
                  [175, 185, 195],
                  [205, 215, 225]])
print("Sales (4 stores × 3 months):")
print(sales)

# Your code here:
# 1. Total sales for each store (hint: axis=1)
print(np.sum(sales, axis=1))


# 2. Average monthly sales across all stores (hint: axis=0)
print(np.mean(sales, axis=0))


# 3. Store with highest total sales (hint: np.argmax)
print(np.argmax(np.sum(sales, axis=1)))

Sales (4 stores × 3 months):
[[150 200 180]
 [220 190 240]
 [175 185 195]
 [205 215 225]]
[530 650 555 645]
[187.5 197.5 210. ]
1


In [27]:
### Reshape. Total element must match
print(np.ones((3, 4)).reshape(2, 6))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [28]:
print(np.arange(1, 25).reshape(3, -1))  ## -1 is for figure it out automatically.

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


In [29]:
### Flattens vs Ravel (Both flattens the np array)
# Flatten returns a COPY (Modifying this does not effects the main array) (Values of elements)
# Revel returns a VIEW (Modifying this effects the original array) (References to the elements)

arr = np.array([[4, 3, 2], [6, 5, 2]])
flattened_arr = arr.flatten()
ravelled_arr = arr.ravel()

print(arr)
print(flattened_arr)
print(ravelled_arr)
print("Updating Flattened Array")
flattened_arr[2] = -1
print(arr)
print(flattened_arr)
print(ravelled_arr)
print("Updating Ravelled Array")
ravelled_arr[2] = -1
print(arr)
print(flattened_arr)
print(ravelled_arr)

[[4 3 2]
 [6 5 2]]
[4 3 2 6 5 2]
[4 3 2 6 5 2]
Updating Flattened Array
[[4 3 2]
 [6 5 2]]
[ 4  3 -1  6  5  2]
[4 3 2 6 5 2]
Updating Ravelled Array
[[ 4  3 -1]
 [ 6  5  2]]
[ 4  3 -1  6  5  2]
[ 4  3 -1  6  5  2]


In [30]:
# Transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.T)
print(matrix.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [31]:
# Your code here:
# 1. Create array 1-24 and reshape to (4, 6)
num_array = np.arange(1, 25)
print(num_array.reshape(4, 6))

# 2. Reshape to (2, 3, 4)
print(num_array.reshape(2, 3, 4))

# 3. Flatten using both methods
print(num_array.flatten())
print(num_array.ravel())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Views vs Copies

Understanding views and copies is CRITICAL for avoiding bugs!

**Analogy:**
- A **view** is like looking through a window—you see the same room as inside
- A **copy** is like taking a photograph—changes to the room don't affect your photo


| Operation | Result |
|-----------|--------|
| Slicing `arr[1:4]` | VIEW |
| reshape() | VIEW |
| ravel() | VIEW |
| transpose `.T` | VIEW |
| Fancy indexing `arr[[1,2,3]]` | COPY |
| flatten() | COPY |
| `.copy()` | COPY |

### Dot Product

The dot product multiplies corresponding elements and sums the results.

$$\vec{a} \cdot \vec{b} = \sum_{i} a_i \times b_i$$

Use `np.dot(a, b)` or `a @ b`.

**Analogy:** Element-wise multiplication is like comparing test scores subject by subject. Dot product is like calculating a weighted total—it combines everything into one number.

In [32]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Two ways to compute dot product
dot1 = np.dot(v1, v2)
dot2 = v1 @ v2

print(f"v1 = {v1}")
print(f"v2 = {v2}")
print(f"np.dot(v1, v2) = {dot1}")
print(f"v1 @ v2 = {dot2}")
print(f"Manual: 1×4 + 2×5 + 3×6 = {1*4 + 2*5 + 3*6}")

v1 = [1 2 3]
v2 = [4 5 6]
np.dot(v1, v2) = 32
v1 @ v2 = 32
Manual: 1×4 + 2×5 + 3×6 = 32


### Element-wise vs Matrix Multiplication

**CRITICAL DISTINCTION:**
- `*` = element-wise multiplication (multiply corresponding elements)
- `@` or `np.dot()` = matrix multiplication (linear algebra)

In [33]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("A =")
print(A)
print("\nB =")
print(B)

A =
[[1 2]
 [3 4]]

B =
[[5 6]
 [7 8]]


In [34]:
print(A * B)
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


### Why Dot Product Matters (Preview)

Dot products are used everywhere in ML:
- Measuring similarity between vectors
- Neural network computations
- Recommendation systems