<a href="https://colab.research.google.com/github/Alok-Senapati/Collab-Notebooks/blob/main/numpy/Numpy%20Indexing%20%26%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
## 1. Slicing -> To Access Contiguous Elements
arr = np.array([2, 4, 3, 1, 7])
print(arr[1:3])
print(arr[:4])
print(arr[2:])
print(arr[:-1])
print(arr[-4:-2])

[4 3]
[2 4 3 1]
[3 1 7]
[2 4 3 1]
[4 3]


In [3]:
## Slicing in 2D Array
mat = np.array([
    [2, 4, 5],
    [6, 9, 1],
    [7, 8, 10],
    [1, 7, 3]
])
## mat[row_slice, col_slice]
print(mat[:2, 0:2])
print(mat[:, :2])
print(mat[:-1, :-1])
print(mat[0:2])

[[2 4]
 [6 9]]
[[2 4]
 [6 9]
 [7 8]
 [1 7]]
[[2 4]
 [6 9]
 [7 8]]
[[2 4 5]
 [6 9 1]]


In [4]:
## Fancy Indexing: Passing a list of indexes to select. The order of elements in output is same as order of input index list
print(arr[[0, 3, 2]])
print(arr[[3, 3, 2, 1, 4, 0]])

[2 1 3]
[1 1 3 4 7 2]


In [5]:
## Matrix Fancy Indexing: mat[row_idx, col_idx]
print(mat[[0, 2], [2, 1]])
print(mat[[2, 2, 1, 0], [1, 0, 0, 2]])
print(mat[:-1, [2, 0, 1]]) ## Slicing + Fancy Indexing

[5 8]
[8 7 6 5]
[[ 5  2  4]
 [ 1  6  9]
 [10  7  8]]


## Element-wise Operations

NumPy performs operations on **every element** simultaneously without explicit loops. This is called **vectorization**.

In [7]:
## List vs Array Behaviour -> Behaves differently with same operation.
print([1, 2, 3] + [3, 4, 5]) ## Concatenation
print(np.array([1, 2, 3]) + np.array([3, 4, 5])) ## Element wise addition

[1, 2, 3, 3, 4, 5]
[4 6 8]


In [8]:
print([1, 2, 3] * 3)
print(np.array([1, 2, 3]) * 3) ## Scalar Multiplication

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [10]:
## Scalar Operation -> Scalar value is broadcasted to operate with each element
arr = np.arange(1, 10)

print(arr + 5)
print(arr * 5)
print(arr - 5)
print(arr / 5)
print(arr // 5)
print(arr % 5)
print(arr ** 2)

[ 6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45]
[-4 -3 -2 -1  0  1  2  3  4]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[0 0 0 0 1 1 1 1 1]
[1 2 3 4 0 1 2 3 4]
[ 1  4  9 16 25 36 49 64 81]


In [18]:
## Element Wise Operation
first = np.array([1, 2, 3, 4])
second = np.array([8, 7, 6, 5])

print(first + second)
print(second - first)
print(first * second)
print(second / first)
print(second // first)
print(second ** first)

[9 9 9 9]
[7 5 3 1]
[ 8 14 18 20]
[8.   3.5  2.   1.25]
[8 3 2 1]
[  8  49 216 625]


In [23]:
## Comparison Operators -> Return Boolean Arrays which can be used as Boolean masks for filtering
scores = np.random.randint(20, 100, size=10)
print(scores)

print(scores > 30)
print(scores >= 45)
print(scores != 74)

## Logical Operators. Always use () while using logical operators for np arrays
print((scores > 30) & (scores < 80))
print((scores < 50) | (scores >= 76))
print(~(scores % 2 == 0))

## Using as boolean mask to filter elements
print(scores[scores > 30])
print(scores[(scores < 50) | (scores >= 76)])

[88 89 52 78 41 65 90 29 97 69]
[ True  True  True  True  True  True  True False  True  True]
[ True  True  True  True False  True  True False  True  True]
[ True  True  True  True  True  True  True  True  True  True]
[False False  True  True  True  True False False False  True]
[ True  True False  True  True False  True  True  True False]
[False  True False False  True  True False  True  True  True]
[88 89 52 78 41 65 90 97 69]
[88 89 78 41 90 29 97]


In [26]:
mat = np.random.randint(20, 100, size=12).reshape(4, 3)

print(mat)
print(mat > 50)
print(mat[mat > 50]) ## Returns Array

[[25 37 28]
 [51 57 48]
 [81 69 89]
 [53 75 34]]
[[False False False]
 [ True  True False]
 [ True  True  True]
 [ True  True False]]
[51 57 81 69 89 53 75]


## Broadcasting

Broadcasting allows NumPy to work with arrays of different shapes by automatically "stretching" smaller arrays.

In [11]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Array + 10:", arr + 10)  # 10 broadcasts to all elements

# Conceptually, this is like:
# [1, 2, 3, 4, 5] + [10, 10, 10, 10, 10] = [11, 12, 13, 14, 15]

Array: [1 2 3 4 5]
Array + 10: [11 12 13 14 15]


### 1D + 2D Broadcasting

A 1D array can broadcast across the rows (or columns) of a 2D array if the shapes are compatible.

In [12]:
# 2D matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 1D array (must match the number of columns)
row = np.array([10, 20, 30])

print("Matrix (2x3):")
print(matrix)
print("\nRow (1D):", row)

print("\nMatrix + Row:")
print(matrix + row)
# The row broadcasts across EACH row of the matrix

Matrix (2x3):
[[1 2 3]
 [4 5 6]]

Row (1D): [10 20 30]

Matrix + Row:
[[11 22 33]
 [14 25 36]]


In [13]:
## An array of lesser dimension can be broadcasted to an array of higher dimention, if and only if
##  The lower dims of the bigger array are either of same shape or either one of them is 1.

arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.array([1, 2, 3, 4])
print(arr1.shape) # (3, 4)
print(arr2.shape) # (4,)

## Broadcasts arr2 to make it shape (1, 4), Now columns are of same shape and one of the row shape is 1, Hence it makes arr2 (3, 4) by repeating column to 3 rows.
print(arr1 + arr2)


(3, 4)
(4,)
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [15]:
arr3 = np.ones((2, 3, 4))
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr3.shape)
print(arr4.shape)

print(arr3 + arr4)

(2, 3, 4)
(3, 3)


ValueError: operands could not be broadcast together with shapes (2,3,4) (3,3) 

In [16]:
arr5 = np.array([[1, 2, 3, 4], [7, 4, 8, 10]])
arr6 = np.array([[3], [7]])

print(arr5.shape)
print(arr6.shape)

print(arr5 + arr6)


(2, 4)
(2, 1)
[[ 4  5  6  7]
 [14 11 15 17]]
