<a href="https://colab.research.google.com/github/Alok-Senapati/Collab-Notebooks/blob/main/numpy/Numpy%20Indexing%20%26%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
## 1. Slicing -> To Access Contiguous Elements
arr = np.array([2, 4, 3, 1, 7])
print(arr[1:3])
print(arr[:4])
print(arr[2:])
print(arr[:-1])
print(arr[-4:-2])

[4 3]
[2 4 3 1]
[3 1 7]
[2 4 3 1]
[4 3]


In [6]:
## Slicing in 2D Array
mat = np.array([
    [2, 4, 5],
    [6, 9, 1],
    [7, 8, 10],
    [1, 7, 3]
])
## mat[row_slice, col_slice]
print(mat[:2, 0:2])
print(mat[:, :2])
print(mat[:-1, :-1])
print(mat[0:2])

[[2 4]
 [6 9]]
[[2 4]
 [6 9]
 [7 8]
 [1 7]]
[[2 4]
 [6 9]
 [7 8]]
[[2 4 5]
 [6 9 1]]


In [7]:
## Fancy Indexing: Passing a list of indexes to select. The order of elements in output is same as order of input index list
print(arr[[0, 3, 2]])
print(arr[[3, 3, 2, 1, 4, 0]])

[2 1 3]
[1 1 3 4 7 2]


In [12]:
## Matrix Fancy Indexing: mat[row_idx, col_idx]
print(mat[[0, 2], [2, 1]])
print(mat[[2, 2, 1, 0], [1, 0, 0, 2]])
print(mat[:-1, [2, 0, 1]]) ## Slicing + Fancy Indexing

[5 8]
[8 7 6 5]
[[ 5  2  4]
 [ 1  6  9]
 [10  7  8]]
