In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------------------- -------------------- 6.3/12.6 MB 32.2 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 28.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 20.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 18.8 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np

In [5]:
## List to numpy array
## Numpy Array: Homogeneous Continuous Array of elements.

my_list = [1, 2, 3, 4, 5]
np_from_list = np.array(my_list)
print(my_list)
print(np_from_list)

print(type(my_list))
print(type(np_from_list))
print(np_from_list.shape)
print(np_from_list.ndim)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>
(5,)
1


In [6]:
## 2D Array
np_arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np_arr_2d)
print(np_arr_2d.shape)
print(np_arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [9]:
sample_list = list(range(1, 10000000))
sample_arr = np.array(sample_list)

In [12]:
%%time
doubled_list = [2 * i for i in sample_list]

CPU times: total: 984 ms
Wall time: 1e+03 ms


In [13]:
%%time
## Using numpy array operations
doubled_arr = sample_arr * 2


CPU times: total: 62.5 ms
Wall time: 54.5 ms


In [14]:
## Creating Numpy Arrays
arr1 = np.zeros(4) ## Vector of 4 zeroes
arr2 = np.ones((4, 5)) ## Matrix of ones with shape [4*5]
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)

print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

[0. 0. 0. 0.]
(4,)
1
float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)
2
float64


In [15]:
arr3 = np.arange(0, 100, 2) ## Similar to range
print(arr3)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)
print(arr3.size)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)
int64
1
50


In [16]:
arr4 = np.linspace(0, 100, 25) ## Linear equispaced floats
print(arr4)
print(arr4.shape)
print(arr4.dtype)
print(arr4.ndim)
print(arr4.size)

[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]
(25,)
float64
1
25
