In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
## List to numpy array
## Numpy Array: Homogeneous Continuous Array of elements.

my_list = [1, 2, 3, 4, 5]
np_from_list = np.array(my_list)
print(my_list)
print(np_from_list)

print(type(my_list))
print(type(np_from_list))
print(np_from_list.shape)
print(np_from_list.ndim)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>
(5,)
1


In [4]:
## 2D Array
np_arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np_arr_2d)
print(np_arr_2d.shape)
print(np_arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [5]:
sample_list = list(range(1, 10000000))
sample_arr = np.array(sample_list)

In [6]:
%%time
doubled_list = [2 * i for i in sample_list]

CPU times: total: 469 ms
Wall time: 464 ms


In [7]:
%%time
## Using numpy array operations
doubled_arr = sample_arr * 2


CPU times: total: 31.2 ms
Wall time: 17.3 ms


In [8]:
## Creating Numpy Arrays
arr1 = np.zeros(4) ## Vector of 4 zeroes
arr2 = np.ones((4, 5)) ## Matrix of ones with shape [4*5]
tensor = np.ones((4, 5, 3)) ## Tensor(3D) of ones
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)

print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[0. 0. 0. 0.]
(4,)
1
float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)
2
float64
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
(4, 5, 3)
3
float64


In [9]:
arr3 = np.arange(0, 100, 2) ## Similar to range
print(arr3)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)
print(arr3.size)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)
int64
1
50


In [10]:
arr4 = np.linspace(0, 100, 25) ## Linear equispaced floats
print(arr4)
print(arr4.shape)
print(arr4.dtype)
print(arr4.ndim)
print(arr4.size)

[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]
(25,)
float64
1
25


In [11]:
arr5 = np.full((3, 4), 20) ## Fill with specific values, creates an matrix of shape (3, 4) and fills it with 20
print(arr5)
print(arr5.shape)
print(arr5.ndim)
print(arr5.dtype)
print(arr5.size)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]
(3, 4)
2
int64
12


In [16]:
## Generating Random Numbers
rand_arr1 = np.random.rand(5) # np array of 5 random values in range [0, 1)
rand_arr2 = np.random.rand(2, 3)  # np array of random values in range [0, 1) of shape (2, 3)
rand_int = np.random.randint(2, 5)   # random integer value in range [2, 5)
rand_arr4 = np.random.randn(4, 5)  # np array of values from standard normal distribution of shape (4, 5)
rand_int_arr = np.random.randint(1, 10, (2, 5)) # np array of random values between 1 to 20 of shape 2 x 5

print(rand_arr1)
print(rand_arr1.shape)
print(rand_arr1.ndim)
print(rand_arr1.dtype)
print(rand_arr1.size)
print("=" * 50)

print(rand_arr2)
print(rand_arr2.shape)
print(rand_arr2.ndim)
print(rand_arr2.dtype)
print(rand_arr2.size)
print("=" * 50)

print(rand_int)
print("=" * 50)

print(rand_arr4)
print(rand_arr4.shape)
print(rand_arr4.ndim)
print(rand_arr4.dtype)
print(rand_arr4.size)

print(rand_int_arr)
print(rand_int_arr.shape)
print(rand_int_arr.ndim)
print(rand_int_arr.dtype)
print(rand_int_arr.size)

[0.21340941 0.09199594 0.80848514 0.41264919 0.78604342]
(5,)
1
float64
5
[[0.94560521 0.46318186 0.06778475]
 [0.77674608 0.00341109 0.03419357]]
(2, 3)
2
float64
6
4
[[ 0.1757466   0.57360281  0.86271662  0.29611491  0.35560799]
 [ 0.48026685  0.32750864  0.49313485  1.52915084  1.63521736]
 [-0.67082408 -0.81685238  1.37794916  0.64240034 -0.60346916]
 [-1.43975076 -0.65634583  0.15891202 -1.12742743 -0.23575188]]
(4, 5)
2
float64
20
[[5 7 8 8 8]
 [6 7 6 4 4]]
(2, 5)
2
int32
10


In [13]:
""" Common Numpy Datatypes
• int64 64-bit integers (default for numbers)
• float64 64-bit floats (default for decimals)
• bool: True/False values
• object: Python objects (Avoid for speed!)
"""

' Common Numpy Datatypes\n• int64 64-bit integers (default for numbers)\n• float64 64-bit floats (default for decimals)\n• bool: True/False values\n• object: Python objects (Avoid for speed!)\n'

In [14]:
## Mixed Types -> NumPy automatically upcasts everything to the most general/safe type that can hold all values.
print(np.array([1, 2.0, 3.5]))
print(np.array([1, 2, True]))
print(np.array([1, 2, True, 4.32]))
print(np.array([1, 2, True, "Harry"]))
print(np.array([1, 2, True, 8.0, "Jack"]))

print(np.array([1, 2.0, 3.5]).dtype)
print(np.array([1, 2, True]).dtype)
print(np.array([1, 2, True, 4.32]).dtype)
print(np.array([1, 2, True, "Harry"]).dtype)
print(np.array([1, 2, True, 8.0, "Jack"]).dtype)

[1.  2.  3.5]
[1 2 1]
[1.   2.   1.   4.32]
['1' '2' 'True' 'Harry']
['1' '2' 'True' '8.0' 'Jack']
float64
int64
float64
<U21
<U32
